---
- hosts: all
  become: yes
  become_user: root
  tasks:
  - name: Install basic Gnome desktop
    apt:
      pkg:
        - gnome-session
        - gdm3
      state: latest
      update_cache: true
  - name: Reboot
    reboot: 